github/octocatalog-diff

spec/octocatalog-diff/integration/integration_helper.rb, spec/octocatalog-diff/integration/pe_enc_spec.rb, spec/octocatalog-diff/integration/puppetmaster_spec.rb, spec/octocatalog-diff/support/httparty/ssl_test_server.rb, spec/octocatalog-diff/tests/puppetdb_spec.rb, spec/octocatalog-diff/tests/spec_helper.rb
This pull request ignores the `#<Errno::ESRCH: No such process>` exception that's being thrown on Travis CI, during the portion of the test that is attempting to kill that process. If the process is already dead, it's fine if we can't kill it.
It also adds a retry around starting the SSL server for some of the integration tests, so that a failure to start the test server has less of a change of failing the job. This seems to be an issue specific to Travis CI and it's intermittent.
=> Ignore any kill errors for the testing SSL server

lib/octocatalog-diff/catalog-util/fileresources.rb, spec/octocatalog-diff/tests/catalog-util/fileresources_spec.rb
This pull request avoids an exception being thrown when:
- Catalog caching is enabled
- The "to" branch is `.`
- The `environments/production` symlink is missing
The changed code checks additional paths, and skips the code that will be problematic when the Puppet repository is not set up as expected.
=> Allow convert_file_resources to work even in absence of environments/production

doc/configuration.md, examples/octocatalog-diff.cfg.rb
This pull request fixes the documentation and example config file.
`settings[:hiera_yaml_file]` is not correct. The correct setting is `settings[:hiera_config]`.
Fixes https://github.com/github/octocatalog-diff/issues/13
Thanks to @eelcomaljaars for the report.
=> hiera_yaml_file -> hiera_config everywhere

doc/advanced-hiera-path-stripping.md, doc/configuration-hiera.md, examples/octocatalog-diff.cfg.rb, lib/octocatalog-diff/catalog-diff/cli.rb, lib/octocatalog-diff/catalog-diff/cli/options/hiera_path.rb, lib/octocatalog-diff/catalog-diff/cli/options/hiera_path_strip.rb, lib/octocatalog-diff/catalog-util/builddir.rb, spec/octocatalog-diff/tests/catalog-diff/cli/options/hiera_path_spec.rb, spec/octocatalog-diff/tests/catalog-diff/cli/options/hiera_path_strip_spec.rb, spec/octocatalog-diff/tests/catalog-util/builddir_spec.rb
This pull request changes the defaults for the Hiera configuration to match the [Puppet control repo template](https://github.com/puppetlabs/control-repo) and the default installation of Puppet Enterprise.
It also introduces a new option `--hiera-path PATH` to specify the relative path to hieradata. This passes through the relative directory to the munged hiera.yaml file. This is an alternative to `--hiera-path-strip PATH` which will reference the settings from the existing hiera.yaml file and subtract the specified path. Since most humans tend to find a positive declaration easier than a negative one, this should simplify the setup for many people.
=> Hiera setup simplification

doc/advanced-hiera-path-stripping.md, examples/octocatalog-diff.cfg.rb
Documentation and example update which adds a reminder not to include a trailing slash on `--hiera-path-strip`.
Fixes https://github.com/github/octocatalog-diff/issues/23
=> Add notes about trailing slashes for --hiera-path-strip

doc/advanced-bootstrap.md, doc/configuration-enc.md
This is a documentation PR inspired by https://github.com/github/octocatalog-diff/issues/27. It documents passing the environment variables to the bootstrap script and the ENC.
Fixes https://github.com/github/octocatalog-diff/issues/27.
=> Document environment variable passing for bootstrap and ENC

lib/octocatalog-diff/catalog-util/bootstrap.rb, spec/octocatalog-diff/tests/catalog-util/bootstrap_spec.rb
This pull request treats the user-supplied bootstrap script as an absolute path when it starts with `/`.
See https://github.com/github/octocatalog-diff/issues/28 for context.
Fixes https://github.com/github/octocatalog-diff/issues/28.
=> Allow bootstrap script to start with slash

doc/dev/releasing.md, octocatalog-diff.gemspec, rake/gem.rb
This allows the version of the gem to be adjusted dynamically from the environment. Used for the internal testing of this code within GitHub, to validate a release with the GitHub Puppet code base before release of a publicly numbered version.
=> Allow alternate version to be specified from command line

lib/octocatalog-diff/catalog-util/builddir.rb, spec/octocatalog-diff/fixtures/repos/preserve-environments/environments/one/hiera.yaml, spec/octocatalog-diff/fixtures/repos/preserve-environments/environments/one/hieradata/common.yaml, spec/octocatalog-diff/fixtures/repos/preserve-environments/environments/one/modules/bar/manifests/init.pp, spec/octocatalog-diff/fixtures/repos/preserve-environments/environments/two/hiera.yaml, spec/octocatalog-diff/fixtures/repos/preserve-environments/environments/two/hieradata/common.yaml, spec/octocatalog-diff/fixtures/repos/preserve-environments/environments/two/modules/bar/manifests/init.pp, spec/octocatalog-diff/integration/preserve_environments_spec.rb, spec/octocatalog-diff/tests/catalog-util/builddir_spec.rb
Fixes the problem in https://github.com/github/octocatalog-diff/issues/35#issuecomment-270070454
/cc @tobias-urdin - The fix was actually pretty easy (https://github.com/github/octocatalog-diff/commit/e3531b38c08e0b4a281ff0f7d1b6b9a8dd0f332f) and then I added a bunch of testing around it. Could you try this branch and see if the issue you reported is fixed?
=> Make hiera configuration work for alternate environments too

lib/octocatalog-diff/catalog-util/bootstrap.rb, lib/octocatalog-diff/catalog-util/cached_master_directory.rb, lib/octocatalog-diff/cli.rb, lib/octocatalog-diff/util/catalogs.rb, spec/octocatalog-diff/integration/catalog_compute_spec.rb, spec/octocatalog-diff/integration/convert_file_resources_spec.rb, spec/octocatalog-diff/integration/pe_enc_spec.rb, spec/octocatalog-diff/integration/preserve_environments_spec.rb, spec/octocatalog-diff/integration/puppetdb_spec.rb, spec/octocatalog-diff/integration/puppetmaster_spec.rb, spec/octocatalog-diff/tests/cli_spec.rb, spec/octocatalog-diff/tests/util/catalogs_spec.rb
Continuing the refactoring - this moves `cli/catalogs` to `util/catalogs` since catalog generation is not really a CLI function. (Later on the `api` will also call `util/catalogs`.)
=> Move cli/catalogs -> util/catalogs

lib/octocatalog-diff/cli.rb, spec/octocatalog-diff/integration/catalog_only_spec.rb
This pull request changes the CLI class to use the catalog API instead of the raw objects. This is done mostly for dog-fooding of the API.
=> Use the catalog API internally

lib/octocatalog-diff/catalog/computed.rb, lib/octocatalog-diff/cli.rb, spec/octocatalog-diff/integration/arbitrary_command_line_spec.rb, spec/octocatalog-diff/integration/bootstrap_script_spec.rb, spec/octocatalog-diff/integration/convert_file_resources_spec.rb, spec/octocatalog-diff/integration/modulepath_spec.rb, spec/octocatalog-diff/integration/preserve_environments_spec.rb, spec/octocatalog-diff/integration/reference_validation_spec.rb, spec/octocatalog-diff/integration/yaml_diff_spec.rb, spec/octocatalog-diff/tests/spec_helper.rb
This pull request changes the CLI class to use the catalog-diff API (and specifically the Diff object) instead of the raw objects. This is done mostly for dog-fooding of the API.
=> Use diff object from API internally

spec/octocatalog-diff/tests/api/v1_spec.rb
This PR fixes the spec test for `lib/octocatalog-diff/api/v1.rb` by naming it properly so it gets run, and adds coverage for the `.config` method as well.
=> Rename file so it gets run and add test for `.config` method

doc/dev/api/v1/objects/diff.md, doc/optionsref.md, lib/octocatalog-diff/api/v1/diff.rb, lib/octocatalog-diff/catalog-diff/display.rb, lib/octocatalog-diff/catalog-diff/display/legacy_json.rb, lib/octocatalog-diff/cli/options/output_format.rb, lib/octocatalog-diff/cli/printer.rb, spec/octocatalog-diff/integration/outputs_spec.rb, spec/octocatalog-diff/tests/api/v1/diff_spec.rb, spec/octocatalog-diff/tests/catalog-diff/display_spec.rb, spec/octocatalog-diff/tests/cli/options/output_format_spec.rb, spec/octocatalog-diff/tests/cli/printer_spec.rb
This PR:
- Changes the default JSON output from an array:
```
["~", "File\f/etc/foo\fparameters\fcontent", ...]
```
to a hash with meaningful keys:
```
{ "diff_type": "~", "type": "File", "title": "/etc/foo", ... }
```
- Adds an output format named `legacy_json` to output the old way.
=> JSON output

doc/advanced-filter.md, doc/optionsref.md, lib/octocatalog-diff/catalog-diff/differ.rb, lib/octocatalog-diff/catalog-diff/filter.rb, lib/octocatalog-diff/catalog-diff/filter/absent_file.rb, lib/octocatalog-diff/catalog-diff/filter/yaml.rb, lib/octocatalog-diff/cli/options/suppress_absent_file_details.rb, spec/octocatalog-diff/integration/file_absent_spec.rb, spec/octocatalog-diff/tests/catalog-diff/differ_spec.rb, spec/octocatalog-diff/tests/catalog-diff/filter/absent_file_spec.rb, spec/octocatalog-diff/tests/catalog-diff/filter/yaml_spec.rb, spec/octocatalog-diff/tests/catalog-diff/filter_spec.rb
This PR changes the "ignore changes to absent file" into a proper, modular filter. There should be no functionality change here.
=> Change the "ignore changes to absent file" to a filter

examples/api/v1/catalog-diff-git-repo.rb, examples/api/v1/catalog-diff-local-files.rb, lib/octocatalog-diff/catalog-diff/differ.rb, spec/octocatalog-diff/integration/examples_spec.rb, spec/octocatalog-diff/tests/catalog-diff/differ_spec.rb
Add example scripts for catalog-diff API.
Also, to match documentation, support regexp for type matches.
=> Add examples for catalog-diff API

lib/octocatalog-diff/catalog-diff/differ.rb, lib/octocatalog-diff/catalog-diff/filter.rb, lib/octocatalog-diff/catalog-diff/filter/absent_file.rb, lib/octocatalog-diff/catalog-diff/filter/compilation_dir.rb, lib/octocatalog-diff/cli/diffs.rb, spec/octocatalog-diff/integration/compilation_dir_spec.rb, spec/octocatalog-diff/tests/catalog-diff/filter/compilation_dir_spec.rb, spec/octocatalog-diff/tests/catalog-diff/filter_spec.rb, spec/octocatalog-diff/tests/cli/diffs_spec.rb
This PR refactors the compilation directory test to be a filter instead of hard-coded within the code. Since this only existed in the CLI code before, this change is necessary to allow API results to take advantage of this code.
=> Compilation directory filter refactor

lib/octocatalog-diff/catalog-diff/differ.rb, lib/octocatalog-diff/cli/diffs.rb, spec/octocatalog-diff/integration/ignore_tags_spec.rb, spec/octocatalog-diff/tests/catalog-diff/differ_spec.rb, spec/octocatalog-diff/tests/cli/diffs_spec.rb
This PR moves the "ignore tagged resources" [Dynamic Ignoring Based On Tags](https://github.com/github/octocatalog-diff/blob/884a6f683c7f9038c5160441dc9fc141a72e1fac/doc/advanced-dynamic-ignores.md) out of the CLI class so it's usable via the API.
=> Move ignore tagged resources out of CLI

lib/octocatalog-diff/catalog-diff/filter.rb, lib/octocatalog-diff/cli/options/filters.rb, spec/octocatalog-diff/tests/catalog-diff/filter_spec.rb, spec/octocatalog-diff/tests/cli/options/filters_spec.rb
Ensure that any user-provided filter names actually exist. Raise a more immediate and less cryptic error if they don't.
=> Filter validation

README.md, doc/CHANGELOG.md
This updates the documentation for the release of 0.99.rc1.
=> Release 0.99.rc1

lib/octocatalog-diff/api/v1/diff.rb, spec/octocatalog-diff/tests/api/v1/diff_spec.rb
This pull request defines the `[]=` method in the `Api::V1::Diff` class.
The method is already called from different parts of the code (eg https://github.com/github/octocatalog-diff/blob/384085155a5324384638ceb6737b24698e758ba2/lib/octocatalog-diff/catalog-diff/display/text.rb#L401-L402), that fail when exercised.
/cc @kpaulisse
=> Add missing []= method

lib/octocatalog-diff/cli.rb, spec/octocatalog-diff/integration/catalog_only_spec.rb, spec/octocatalog-diff/integration/integration_helper.rb, spec/octocatalog-diff/integration/reference_validation_spec.rb, spec/octocatalog-diff/tests/spec_helper.rb
This PR updates some of the integration logic to return additional details for analysis. For example a catalog-diff result will now make both catalogs available for further testing.
Also, make the exit status for `--catalog-only` consistent with the CLI. 0 = success, 1 = not.
/cc https://github.com/github/octocatalog-diff/pull/74 since some of the work was originally done there.
=> Integration refactors - exit codes, more information

lib/octocatalog-diff/catalog-diff/display/text.rb, spec/octocatalog-diff/integration/text_diff_spec.rb, spec/octocatalog-diff/tests/catalog-diff/display/text_spec.rb
This pull request adds better displays of whitespace-only diffs in strings.
Old:
```
*******************************************
Authorized_key[some-user] =>
parameters =>
key =>
```
New:
```
*******************************************
Authorized_key[some-user] =>
parameters =>
key =>
- asldfjlsdfkjaflkajsfadlsfkja
\ No newline at end of file
+ asldfjlsdfkjaflkajsfadlsfkja
```
=> Whitespace diff display

doc/advanced.md
This PR just fixes the minor documentation link typo on advanced.md
=> [minor] [doc] fix link to advanced-environments.md

doc/optionsref.md, lib/octocatalog-diff/catalog/puppetmaster.rb, lib/octocatalog-diff/cli/options/puppet_master_timeout.rb, spec/octocatalog-diff/tests/cli/options/puppet_master_timeout_spec.rb
Add a command line option to specify the timeout for retrieving a catalog from a Puppet master.
Don't ask me why. 😉 🙄
=> Command line option for Puppet Master timeout

examples/octocatalog-diff.cfg.rb
Clarifies the example configuration file to indicate it sets the more popular options, but that any command line option can be set in this way.
/cc https://github.com/github/octocatalog-diff/issues/89
=> Add note to example configuration that it's not exhaustive

lib/octocatalog-diff/catalog-util/builddir.rb, lib/octocatalog-diff/catalog-util/command.rb, lib/octocatalog-diff/catalog/computed.rb, spec/octocatalog-diff/integration/preserve_environments_spec.rb, spec/octocatalog-diff/tests/catalog-util/builddir_spec.rb, spec/octocatalog-diff/tests/catalog/computed_spec.rb
This pull request changes the behaviour of the `--environment` flag when used on its own.
Solve the problem described in #85. Allows the `--environment` flag to be used without the `--preserve-environments` flag. 
Tries to maintain the current functionality by ignoring this parameter when used with `--create-symlinks`. 
Doesn't modify the existing behaviour of `--preserve-environments`
=> #85: Feature/use environment without preserve

lib/octocatalog-diff/catalog/computed.rb, lib/octocatalog-diff/util/puppetversion.rb
This pull request fixes #93 
It adds an optional param to the version check method which, if supplied will allow the command to retain extra environment variables as expected
/cc #93 @kpaulisse
=> Fixed #93 Make puppet version check respect env vars

doc/advanced-dynamic-ignores.md, lib/octocatalog-diff/catalog-diff/differ.rb, spec/octocatalog-diff/fixtures/catalogs/include-tags-new.json, spec/octocatalog-diff/fixtures/catalogs/include-tags-old.json, spec/octocatalog-diff/integration/include_tags_spec.rb
Fixes https://github.com/github/octocatalog-diff/issues/97
This was left over from pre-release days where `--ignore-tags` meant something else. The relevant option is now `--include-tags` / `--no-include-tags` and the filtering is done elsewhere in the code.
=> Remove legacy exclusion of tags

lib/octocatalog-diff/catalog-util/builddir.rb, spec/octocatalog-diff/fixtures/repos/default/config/hiera-backend-as-string.yaml, spec/octocatalog-diff/tests/catalog-util/builddir_spec.rb
Fixes https://github.com/github/octocatalog-diff/issues/107
This allows the hiera.yaml file to declare a single backend as a string rather than an array, since Puppet allows that.
=> Support hiera.yaml backend declared as a string instead of array

lib/octocatalog-diff/catalog-util/command.rb
The arguments for puppet invocations are not longer explicitely split on
white-spaces.  This means that only one argument is added for ENC, while
this should be two (--node_terminus and --external_nodes).  Just
properly split the arguments.
=> Split arguments added for ENC

.travis.yml, doc/dev/integration-tests.md, doc/requirements.md, lib/octocatalog-diff/api/v1/override.rb, lib/octocatalog-diff/bootstrap.rb, lib/octocatalog-diff/catalog-diff/differ.rb, lib/octocatalog-diff/catalog-diff/display/text.rb, lib/octocatalog-diff/catalog-util/builddir.rb, lib/octocatalog-diff/catalog-util/command.rb, lib/octocatalog-diff/catalog/computed.rb, lib/octocatalog-diff/catalog/puppetdb.rb, lib/octocatalog-diff/catalog/puppetmaster.rb, lib/octocatalog-diff/cli.rb, lib/octocatalog-diff/cli/options/puppet_master_timeout.rb, lib/octocatalog-diff/facts/puppetdb.rb, lib/octocatalog-diff/puppetdb.rb, lib/octocatalog-diff/util/catalogs.rb, lib/octocatalog-diff/util/httparty.rb, spec/octocatalog-diff/fixtures/repos/fact-overrides-datatypes/modules/test/templates/test.erb, spec/octocatalog-diff/integration/fact_override_spec.rb, spec/octocatalog-diff/integration/integration_helper.rb, spec/octocatalog-diff/support/httparty/ssl_test_server.rb, spec/octocatalog-diff/tests/api/v1/override_spec.rb, spec/octocatalog-diff/tests/catalog-diff/display/text_spec.rb, spec/octocatalog-diff/tests/catalog/puppetmaster_spec.rb, spec/octocatalog-diff/tests/cli/options/puppet_master_timeout_spec.rb, spec/octocatalog-diff/tests/spec_helper.rb
This PR makes updates to the Travis configuration and rubocop settings to be compatible with Ruby 2.4. Also, some updates in the code are made to prefer `Integer` over `Fixnum`.
=> Ruby 2.4 compatibility

doc/advanced-override-facts.md, lib/octocatalog-diff/api/v1/override.rb, lib/octocatalog-diff/catalog-util/builddir.rb, lib/octocatalog-diff/catalog-util/enc.rb, lib/octocatalog-diff/facts.rb, spec/octocatalog-diff/integration/fact_override_spec.rb, spec/octocatalog-diff/tests/api/v1/override_spec.rb, spec/octocatalog-diff/tests/catalog-util/builddir_spec.rb, spec/octocatalog-diff/tests/catalog-util/enc_spec.rb, spec/octocatalog-diff/tests/facts_spec.rb
This PR is an enhancement to the fact override and ENC override features. Before you had to type the exact name of the parameter or key to override. With this change you are allowed to enter a regular expression for the key name, and all found keys matching that regular expression will be overridden.
Example:
```
octocatalog-diff [options] --to-fact-override "/^ec2_/=(nil)" would delete all facts that start with "ec2_".
=> Override facts and ENC parameters identified with a regular expression

lib/octocatalog-diff/catalog-util/fileresources.rb, spec/octocatalog-diff/fixtures/repos/regressions/README.md, spec/octocatalog-diff/fixtures/repos/regressions/hiera.yaml, spec/octocatalog-diff/fixtures/repos/regressions/hieradata/common.yaml, spec/octocatalog-diff/fixtures/repos/regressions/manifests/site.pp, spec/octocatalog-diff/fixtures/repos/regressions/modules/file_no_parameters/manifests/init.pp, spec/octocatalog-diff/integration/regressions_spec.rb
This PR creates a "regression" integration test, for those little bugs that we want to make sure don't appear again. The first one is courtesy of https://github.com/github/octocatalog-diff/pull/122, and the contributed fix will be merged with this PR as well.
=> Create integration test for regressions and fix resources with no parameters

lib/octocatalog-diff/catalog-util/fileresources.rb
This pull request fixes: NoMethodError: undefined method `key?' for nil:NilClass with this kind of declaration:
```puppet
file { '/path/to/purge-this-dir/except-this-file':
}
```
=> Handle File resources with no parameters

lib/octocatalog-diff/cli/options.rb, lib/octocatalog-diff/cli/options/fact_file.rb, lib/octocatalog-diff/facts.rb, spec/octocatalog-diff/fixtures/facts/valid-facts-different-ip.yaml, spec/octocatalog-diff/integration/fact_file_by_branch_spec.rb, spec/octocatalog-diff/tests/cli/options/fact_file_spec.rb, spec/octocatalog-diff/tests/facts_spec.rb
This pull request adds `--to-fact-file` and `--from-fact-file` in case one desires to analyze the difference in catalogs based on the facts used. This can be used, for example, to validate an upgrade of puppet agent version or facter version.
=> Fact file per branch

lib/octocatalog-diff/facts.rb, lib/octocatalog-diff/util/util.rb, spec/octocatalog-diff/tests/util/util_spec.rb
This PR adds a utility class, with a "deep dupe" function that's used for the facts.
This work was done as part of https://github.com/github/octocatalog-diff/pull/125 to make all of the internal CI within GitHub work properly, but is separated out here for easier review.
=> Create and implement utility class

lib/octocatalog-diff/cli/options/save_catalog.rb, lib/octocatalog-diff/util/catalogs.rb, spec/octocatalog-diff/tests/cli/options/save_catalog_spec.rb, spec/octocatalog-diff/tests/util/catalogs_spec.rb
This PR adds `--to-save-catalog <filename>` and `--from-save-catalog <filename>` to save the JSON files from the intermediate catalogs. This is mostly useful for debugging, although in some workflows it may be handy to keep them around for further analysis as well.
=> Add option to save catalogs when catalog-diff'ing

doc/optionsref.md, lib/octocatalog-diff/cli/options.rb, rake/doc.rb
This PR updates the script that builds the auto-generated documentation to include options that are specified with `--to-<whatever>` and `--from-<whatever>` when it builds the options reference page. This PR also includes the auto-rebuild of that page, adding several options to the details that were improperly not listed there before.
=> Auto-generated documentation update

lib/octocatalog-diff/facts/yaml.rb, spec/octocatalog-diff/fixtures/facts/unstructured.yaml, spec/octocatalog-diff/tests/facts/yaml_spec.rb
This PR allows fact files generated with `facter -y` to be usable by octocatalog-diff.
The facter-generated facts don't have "name" and "values" keys like Puppet facts do.
=> Allow YAML facts in "facter -y" format

lib/octocatalog-diff/cli/options/fact_file.rb, spec/octocatalog-diff/integration/fact_file_by_branch_spec.rb, spec/octocatalog-diff/tests/cli/options/fact_file_spec.rb
This PR removes a bug whereby `--to-fact-file <filename>` (with no `--from-fact-file` specified) would have caused that fact file to be used for both the "from" and the "to" catalogs.
=> Fact file should not be global

lib/octocatalog-diff/catalog-util/builddir.rb, lib/octocatalog-diff/catalog/computed.rb, lib/octocatalog-diff/util/parallel.rb, lib/octocatalog-diff/util/scriptrunner.rb
To know what created a temporary directory a prefix is
a good indicator. The default of `d` is not very useful.
=> Prefix tmpdirs with ocd-

doc/CHANGELOG.md, lib/octocatalog-diff/catalog-util/fileresources.rb, spec/octocatalog-diff/fixtures/repos/convert-resources/new/manifests/site.pp, spec/octocatalog-diff/fixtures/repos/convert-resources/new/modules/test/manifests/array1.pp, spec/octocatalog-diff/fixtures/repos/convert-resources/new/modules/test/manifests/array2.pp, spec/octocatalog-diff/fixtures/repos/convert-resources/new/modules/test/manifests/array3.pp, spec/octocatalog-diff/fixtures/repos/convert-resources/old/manifests/site.pp, spec/octocatalog-diff/fixtures/repos/convert-resources/old/modules/test/manifests/array1.pp, spec/octocatalog-diff/fixtures/repos/convert-resources/old/modules/test/manifests/array2.pp, spec/octocatalog-diff/fixtures/repos/convert-resources/old/modules/test/manifests/array3.pp, spec/octocatalog-diff/integration/convert_file_resources_spec.rb, spec/octocatalog-diff/tests/catalog-util/fileresources_spec.rb
This PR expands the "compare file text" option, which back-fills the actual text of a file into the catalog so that comparison can occur. The change here enables arrays as well:
```
file { '/tmp/some-file.txt':
source => ['puppet:///modules/test/some-file.txt.special', 'puppet:///modules/test/some-file.txt'], 
}
```
Fixes https://github.com/github/octocatalog-diff/issues/150
=> Expand file text comparison to cover arrays of sources

README.md, doc/advanced-environment-variables.md, lib/octocatalog-diff/catalog-util/builddir.rb, lib/octocatalog-diff/catalog/computed.rb, lib/octocatalog-diff/util/parallel.rb, lib/octocatalog-diff/util/scriptrunner.rb, lib/octocatalog-diff/util/util.rb, spec/octocatalog-diff/tests/catalog/computed_spec.rb, spec/octocatalog-diff/tests/util/parallel_spec.rb, spec/octocatalog-diff/tests/util/scriptrunner_spec.rb, spec/octocatalog-diff/tests/util/util_spec.rb
This PR addresses the problem reported in https://github.com/github/octocatalog-diff/issues/146 by eliminating the use of `at_exit` within parallelized/forked processes. The new design ensures that the temporary directories are properly cleaned, whether parallelization is enabled or not.
Serial execution:
- (TASK: (create temp dir) (do its thing) (remove temp dir at exit))
- (TASK: (create temp dir) (do its thing) (remove temp dir at exit))
- (TASK: (create temp dir) (do its thing) (remove temp dir at exit))
- at_exit: Remove temp dirs
Parallel execution:
- Create temp dir
- Parallel/fork:
- Task that uses temp dir
- Task that uses temp dir
- Task that uses temp dir
- Clean up temp dir
=> When running in parallel/fork mode, properly clean temporary directories

lib/octocatalog-diff/puppetdb.rb, spec/octocatalog-diff/tests/puppetdb_spec.rb
This pull request adds basic auth support for puppetdb URLs.
We have a moderately unique puppet setup (though remarkably close to
github's setup, in some ways). We run puppetdb behind a proxy that is
secured with basic auth (and we will eventually be submitting patches
upstream to puppet). This commit allows octocatalog-diff to parse a basic
auth username, and password from a URL.
- [✓] Make sure that all of the tests pass, and fix any that don't. Just run `rake` in your checkout directory, or review the CI job triggered whenever you push to a pull request.
- [✓] Make sure that there is 100% [test coverage](https://github.com/github/octocatalog-diff/blob/master/doc/dev/coverage.md) by running `rake coverage:spec` or ignoring untestable sections of code with `# :nocov` comments. If you …
=> Add support for puppetdb behind basic auth

doc/optionsref.md, lib/octocatalog-diff/cli/options.rb, lib/octocatalog-diff/cli/options/puppet_master_ssl_ca.rb, lib/octocatalog-diff/cli/options/puppet_master_ssl_client_cert.rb, lib/octocatalog-diff/cli/options/puppet_master_ssl_client_key.rb, lib/octocatalog-diff/cli/options/puppetdb_ssl_ca.rb, lib/octocatalog-diff/cli/options/puppetdb_ssl_client_cert.rb, lib/octocatalog-diff/cli/options/puppetdb_ssl_client_key.rb, lib/octocatalog-diff/cli/options/puppetdb_ssl_client_password.rb, lib/octocatalog-diff/cli/options/puppetdb_ssl_client_password_file.rb, lib/octocatalog-diff/cli/options/puppetdb_url.rb
Some options have the same weight, and updating the document was causing flapping in the ordering of the options. This PR adds an additional sub-weight within a group of weighted options to keep ordering consistent. This is implemented across the puppet and puppetDB SSL credential options.
=> Provide ordering within a given option weight

lib/octocatalog-diff/catalog-util/builddir.rb, spec/octocatalog-diff/fixtures/cli-configs/fact-file.rb, spec/octocatalog-diff/integration/fact_file_by_branch_spec.rb, spec/octocatalog-diff/integration/integration_helper.rb
This PR adds an integration test to ensure that command line arguments `--to-fact-file` and `--from-fact-file` override any facts that were specified in the `.octocatalog-diff.cfg.rb` file. The bug where `:fact_file` in the settings took precedence over a command-line override for facts is also fixed here.
Fixes https://github.com/github/octocatalog-diff/issues/139.
=> Add integration test for CLI fact override being used over config file

lib/octocatalog-diff/catalog-diff/filter.rb, lib/octocatalog-diff/catalog-diff/filter/single_item_array.rb, spec/octocatalog-diff/fixtures/catalogs/filter-single-item-array-1.json, spec/octocatalog-diff/fixtures/catalogs/filter-single-item-array-2.json, spec/octocatalog-diff/integration/filter_single_item_array.rb, spec/octocatalog-diff/tests/catalog-diff/filter/single_item_array_spec.rb
This pull request adds a filter to treat an object the same as a single array containing that object. This difference can appear between some versions of Puppet but it really doesn't reflect an actual difference.
With filter off, this is a difference:
```
old: { notify: "Service[foo]" }
new: { notify: [ "Service[foo]" ] }
```
With the filter turned on, the above example is not a difference.
Fixes https://github.com/github/octocatalog-diff/issues/166
=> Add filter to treat an object the same as a single array containing that object

lib/octocatalog-diff/cli/options.rb
This pull request requires that all command line options have a "weight" to control their order.
This showed up as an incomplete test coverage result, that no options were using the "default weight". That's great, meaning all options have a specified weight. That's what we want, so this PR replaces the "default weight" code with an error message, to provide early warning if someone adds an option and doesn't supply a weight.
=> Require that all options have a specified weight

.travis.yml, doc/dev/api/v1/calls/catalog-diff.md, lib/octocatalog-diff/catalog-diff/differ.rb, spec/octocatalog-diff/integration/ignore_regexp_spec.rb, spec/octocatalog-diff/tests/catalog-diff/differ_spec.rb
This PR solves two reported issues regarding regular expression handling and ignores.
Fixes https://github.com/github/octocatalog-diff/issues/175. Regular expressions were not supported for attributes which explains the error that was reported. Now regular expressions are supported.
Fixes https://github.com/github/octocatalog-diff/issues/183. The "no newline at end of file" is now ignored if it appears in BOTH the "from" and "to" diffs because it's not really a difference in that case. (If it appears in one but not the other, it's still a difference, and it would need to be explicitly ignored.)
/cc @baurmatt who reported both of these issues. Care to give this branch a try with your use cases?
=> Better regular expression attribute handling

doc/dev/api/v1/objects/diff.md, lib/octocatalog-diff/catalog-diff/filter/compilation_dir.rb, script/git-pre-commit, spec/octocatalog-diff/fixtures/catalogs/compilation-dir-1.json, spec/octocatalog-diff/fixtures/catalogs/compilation-dir-2.json, spec/octocatalog-diff/tests/catalog-diff/filter/compilation_dir_spec.rb
We were having some compilation dir differences in our catalog diff because of several use cases that weren't covered by the current `CompilationDir`.
This change implements a different way of checking for the compilation dir so that `CompilationDir` supports complex parameter values (ie nested hashes/arrays) and/or strings containing the compilation dir more than once.
To be noted that the chosen implementation might be much slower than the original algorithm because it defensively dups the parameter values. This might be problematic, and I'm open to suggestion on how to better implement this feature.
As a bonus I'm including a small minor fix of the API documentation of the diff object :)
=> Enhance CompilationDir to filter out cases outlined in #187 & #188

.travis.yml, doc/optionsref.md, lib/octocatalog-diff/cli.rb, lib/octocatalog-diff/cli/options.rb, lib/octocatalog-diff/cli/options/hostname.rb, octocatalog-diff.gemspec, spec/octocatalog-diff/tests/cli/options/hostname_spec.rb
This pull request changes the hostname option to accept a string of multiple, comma separated hosts to diff and runs the diffs in parallel.
This changeset allows for octocatalog-diff to run against multiple hosts without having to resort to using some sort of loop (e.g. bash for loop) to iterate against the hosts.  My team currently uses octocatalog-diff in a CI setup to verify changes against multiple hosts before pushing up changes to our production branch, and it is currently both slow and somewhat inelegant to implement.  
These changes allow users to set up a CI system to run against many hosts to get a better picture of how changes might affect the overall environment by adding multiple hosts to the `-n` or `--hostname` option in a comma separated list, e.g.
```bash
octocatalog-diff …
```
=> Allow `--hostname` to receive a comma separated list of hosts and work on them in parallel

lib/octocatalog-diff/catalog.rb
This pull request changes the `Catalog validation` functionality.
The `Apache` httpd server is well known to be THE software that has different names between RHEL based OS (`httpd`) and Debian + others ones (`apache2`).
For this kind of issue, Puppet allows you to add an `alias` parameter on any resource and this works fine in `octocatalog-diff`.
The Apache module we use (`puppetlabs-apache`,  "version": "2.3.0") defines the `name` parameter and not the `alias`. Then the catalog validation fails in our case (`puppetlabs-apache` + `voxpupuli/puppet-puppetboard:4.0.0`)
To work around this limitation, I added the `name` parameter to the `resources_hash` object if it exists.
=> Add 'name' parameter to the 'resource_hash' for validate_references

.github/CONTRIBUTING.md
This pull request changes a reference to roadmap.md in CONTRIBUTING.md. The first reference to it in the contributers guide is correct, I think the `/doc` prefix was just accidentally left out.
Please let me know if you see any problems with this/other things to improve.
=> Fix broken link to roadmap in CONTRIBUTING.md

README.md
This PR updates the author/owner statement to reflect the role of GitHub's SRE team in the maintainership of octocatalog-diff.
=> Update the author/owner statement

.github/workflows/main.yml
=> Setup CI on Actions

README.md
=> The entire purpose of this commit is so that I can force CI to run

lib/octocatalog-diff/catalog-diff/differ.rb, spec/octocatalog-diff/tests/catalog-diff/differ_spec.rb
This pull request introduces hiding of Sensitive data output.
Puppet now has type Sensitive, which hides the content from logs, etc. Hide it similarly in output of octocatalog-diff, by using a trivial hash so that any diff will still be show.
See also: https://puppet.com/docs/puppet/5.3/lang_data_sensitive.html
=> Hide sensitive parameters

lib/octocatalog-diff/catalog-diff/differ.rb
This pull request introduces support for Hashdiff version 1.0.0.
When using Hashdiff version 1.0.0, octocatalog-diff failed with the following error:
`uninitialized constant OctocatalogDiff::CatalogDiff::Differ::HashDiff (NameError)`.
See also: https://github.com/liufengyun/hashdiff/issues/45
Hashdiff 1.0.0 was released on July, 15 2019 and replaced the constant "HashDiff" with "Hashdiff".
This commit fixes this error and keeps octocatalog-diff backwards compatible to older versions
of HashDiff.
=> Add Support for Hashdiff 1.0.0

lib/octocatalog-diff/util/parallel.rb, spec/octocatalog-diff/tests/util/parallel_spec.rb
This pull request fixes erroneously waited pids inside the OctocatalogDiff::Util::Parallel.run_tasks_parallel method.
I was testing parallel runs with a comma separated list of hosts in the -n option. It consistently failed if I ran without the --no-parallel flag with the following error:
```
octocatalog-diff -d -n prdthing0028.unix.org,prdthing0026.unix.org --parallel
...
D, [2019-02-18T17:50:20.427185 #17245] DEBUG -- : File[/opt/puppetlabs/facter/facts.d/previous_puppet_mode.txt] @ environments/production/modules/puppet_conf/manifests/init.pp:8
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/diffy-3.3.0/lib/diffy/diff.rb:166:in `system': No child processes - Another thread waited the process started by system(). (Errno::ECHILD)
from …
```
=> Fix multi-node list with parallel mode

lib/octocatalog-diff/catalog-util/fileresources.rb, spec/octocatalog-diff/tests/catalog-util/fileresources_spec.rb
Recent versions of Puppet support glob expansion in the environment specified modulepath. This change is required for environments which take advantage of this support.
=> Add glob support for modulepath

doc/advanced-ignores.md, lib/octocatalog-diff/catalog-diff/differ.rb, spec/octocatalog-diff/fixtures/catalogs/ignore-parameter-set-1.json, spec/octocatalog-diff/fixtures/catalogs/ignore-parameter-set-2.json, spec/octocatalog-diff/tests/catalog-diff/differ_spec.rb
This pull request introduces new functionality to the `--ignore` option, allowing array values to parameters to be ignored if they have set equality.
Resources may accept array parameters but may not change behavior depending on the order of those parameters. In those situations it would be good to be able to ignore changes due only to array ordering.
=> Add set quality comparison to ignore filter

doc/optionsref.md, lib/octocatalog-diff/catalog-diff/differ.rb, lib/octocatalog-diff/cli.rb, lib/octocatalog-diff/cli/options/use_lcs.rb, spec/octocatalog-diff/tests/catalog-diff/differ_spec.rb, spec/octocatalog-diff/tests/cli/options/use_lcs_spec.rb, spec/octocatalog-diff/tests/cli_spec.rb
Add a CLI option (--[no-]use-lcs) so the usage of the LCS algo when comparing arrays can be switched on and off. The default is to keep it on as it's has been so far.
Closes #207
=> Add --[no-]use-lcs

doc/advanced-environments.md, doc/advanced-puppet-master.md, doc/configuration-puppet.md, doc/configuration.md, doc/dev/integration-tests.md, doc/dev/releasing.md, doc/dev/run-from-branch.md, doc/installation.md
This pull request updates numbering and indentation of several docs.
While using these docs I noticed that a lot of the alignment in lists was off, causing the numbering to be undesired:
I went through and:
- Changed the `0.` to `1.` because otherwise the numeric lists are 0-based.
- Indented where needed so that the list items are rendered correctly.
I didn't make any changes to content.
All of the updated docs look correct to me when viewed through the GitHub UI on my branch.
=> Fix indent and numbering in several docs

lib/octocatalog-diff/facts/json.rb, spec/octocatalog-diff/fixtures/facts/encoded-facts.json, spec/octocatalog-diff/tests/facts/json_spec.rb
This pull request allows JSON facts to come in the following format without double-encoding them. You can get facts structured like this by running `puppet facts find $(hostname)`:
```json
{
"name":"rspec-node.abc.github.net",
"values":{
"apt_update_last_success":1458162123,
"architecture":"amd64",
"datacenter":"xyz",
"fqdn":"rspec-node.xyz.github.net",
"_timestamp":"2014-12-02 14:56:20 -0600"
}
}
```
The YAML fact handler already had logic that dealt with this case, but the JSON handler didn't. So if you submitted the above JSON file in `--fact-file` it would end up double-encoding them internally:
```json
{
"name":"unknown.node",
"values":{
"name": "rspec-node.abc.github.net",
"values":{
"apt_update_last_success":1458162123,
"architecture":"amd64",
"datacenter":"xyz", …
```
=> Handle JSON facts structured as name/values

doc/advanced-compare-file-text.md, doc/optionsref.md, lib/octocatalog-diff/catalog-util/fileresources.rb, lib/octocatalog-diff/cli/options/compare_file_text.rb, spec/octocatalog-diff/fixtures/catalogs/catalog-test-file-v4-tagged.json, spec/octocatalog-diff/fixtures/repos/convert-resources/broken/modules/test/manifests/init.pp, spec/octocatalog-diff/integration/convert_file_resources_spec.rb, spec/octocatalog-diff/tests/catalog-util/fileresources_spec.rb
This pull request pertains to the feature of `octocatalog-diff` that substitutes the text of static files in place of the `source` attribute. This PR adds:
1. Bug fix - Do not error when the problem is with the "from" catalog and not the "to" catalog
2. Feature - Allow a tag to disable the feature on a per-resource basis
3. Improvement - Improve error message for broken reference
4. Docs - Create documentation for the original feature and the addition made in this PR
Unit tests were added for the new option and functionality, and of course coverage is 100%. Integration tests were also added for the new command line options and the overall disablement of the feature for the "from" catalog.
Specific details about the changes:
This change is partly motivated some work to fix broken `source …
=> Update capability and docs of --compare-file-text

doc/CHANGELOG.md
This pull request changes documentation.
The most recent few entries in the changelog have broken HTML, causing the table to mis-render. This change adds the missing <td> tags.
[no relavent checklist items for documentation-only changes]
=> fix broken HTML in changelog

lib/octocatalog-diff/catalog-diff/differ.rb
This pull request adds support for Nil values for resources in the catalog. Currently if any resource has a parameter explicitly set to undef / nil, octocatalog-diff raises an exception along the lines of:
```
bundler: failed to load command: octocatalog-diff (/builds/puppet/control-repo/vendor/bundle/bin/octocatalog-diff)
RuntimeError: Bug (please report): Unexpected data structure in hashdiff_result: ["+", "Class\fSomeClass\fparameters\fconfig\fSomeResoruce\fSomekey", nil]
/builds/puppet/control-repo/vendor/bundle/gems/octocatalog-diff-2.1.0/lib/octocatalog-diff/catalog-diff/differ.rb:569:in `block in hashdiff_initial'
```
Having certain resource values is supported in puppet and is useful to certain patterns where we set a parameter if certain complex business logic is met otherwise …
=> Support nil / undef values for resource params

doc/advanced-compare-file-text.md, lib/octocatalog-diff/cli/options/compare_file_text.rb, lib/octocatalog-diff/util/catalogs.rb, spec/octocatalog-diff/integration/convert_file_resources_spec.rb, spec/octocatalog-diff/tests/cli/options/compare_file_text_spec.rb, spec/octocatalog-diff/tests/util/catalogs_spec.rb
This pull request modifies the `--compare-file-text` option, which was previously just a binary option, to accept an additional parameter. There are now 3 behaviors:
- `--compare-file-text` -- Like before, enables the feature
- `--no-compare-file-text` -- Like before, disables the feature
- `--compare-file-text=force` -- New! Enables the feature, and doesn't let it be auto-disabled
We need this behavior because we're using `--catalog-only` in our workflow, and this currently auto-disables the feature because the second catalog in the non-existent diff is a "NoOp" catalog. With this change, our generated catalog will be populated with the content of static files rather than a reference to them, which is what we want.
I chose this implementation because it preserves existing behavior while …
=> Add "force" option for compare-file-text

doc/advanced-filter.md, lib/octocatalog-diff/catalog-diff/filter.rb, lib/octocatalog-diff/catalog-diff/filter/equivalent_array_no_datatypes.rb, spec/octocatalog-diff/fixtures/catalogs/filter-equivalent-array-1.json, spec/octocatalog-diff/fixtures/catalogs/filter-equivalent-array-2.json, spec/octocatalog-diff/integration/filter_equivalent_array_no_datatypes_spec.rb, spec/octocatalog-diff/tests/catalog-diff/filter/equivalent_array_no_datatypes_spec.rb
This pull request adds a new filter called `EquivalentArrayNoDatatypes` which suppresses diffs like this one:
```
Exec[my-command-here] =>
parameters =>
returns =>
- ["0", "1"]
+ [0, 1]
```
Specifically, this implementation treats the string, integer, and float values of a given number as the same ("1" == 1 == 1.0) and treats the string representation of a symbol as the same as the string (":foo" == :foo).
Unit tests are updated to cover this filter and an integration test has been added. Filter documentation has also been updated.
=> Add EquivalentArrayNoDatatypes filter

.github/workflows/main.yml
This pull request removes ruby 2.5 from matrix CI testing.
=> Deprecate ruby 2.5 from matrix testing

.github/workflows/release.yml
This pull request adds a release action for GPR. This should be extended later to also cover rubygems. The action will build and push the artifact to GPR when tags are pushed. There's also a workflow dispatch that will allow for manual queues of the release action, where the artifact will be built, but not pushed. Instead, on workflow_dispatch, the artifact will be uploaded to the artifact run. 
=> Add release action for GPR

.github/dependabot.template.yml
=> Remove unneeded registry

lib/octocatalog-diff/catalog-diff/display/text.rb, lib/octocatalog-diff/catalog-util/builddir.rb
=> limiting group matches to 1000 chars at most

lib/octocatalog-diff/catalog-util/command.rb, spec/octocatalog-diff/tests/util/parallel_spec.rb
=> CodeQL - Limit polynomial regex to only match 1000 characters at most

.github/workflows/main.yml, .github/workflows/release.yml
=> Resolve codeql warnings

examples/octocatalog-diff.cfg.rb, lib/octocatalog-diff/catalog-util/command.rb, lib/octocatalog-diff/cli.rb, lib/octocatalog-diff/cli/options/storeconfigs_backend.rb, spec/octocatalog-diff/tests/cli/options/storeconfigs_backend_spec.rb, spec/octocatalog-diff/tests/cli_spec.rb
This pull request adds the ability to set the `storeconfigs_backend` option.  This allows for the selection of alternate backends for storing catalog data.
The change allows the `octocatalog-diff` command to now accept the paramater `--storeconfigs-backend [puppetdb|yaml|json]` which sets the terminus for storeconfigs on the underlying `puppet catalog compile` command.
The default for `storeconfigs_backend` has been defaulted to `puppetdb` to maintain backwards compatibility.
=> Add ability to set storeconfig_backends
